version: '3.8'

services:
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
      target: dev
    ports:
      - 8888:8080
      - 2345:2345
    volumes:
      - ./server/:/app
  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    #  target: dev
    volumes:
      - ./client:/app
    ports:
      - 3434:3000